# Site settings
title: Absolute Clean Fleet
description: >-
  Serving our community since 2018
contact:
  email: contact@absolutecleanfleet.com
  phone: 555-555-1234
credentials:
  - Commercially Insured for Liability
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-assets
  - jekyll-seo-tag
  - kramdown
  - uglifier

source: src
destination: www
markdown: kramdown

compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
